CREATE TABLE `footballleagues.team_info.team_info` (
    id INT64 NOT NULL,
    name STRING NOT NULL,
    country STRING NOT NULL,
    founded INT64,
    venue_name STRING,
    venue_address STRING,
    venue_city STRING,
    venue_capacity INT64,
    venue_surface STRING,
    league_id INT64 NOT NULL,
    league_name STRING NOT NULL,
    league_country STRING NOT NULL,
    rank INT64 NOT NULL,
    points INT64 NOT NULL,
    overall_wins INT64 NOT NULL,
    overall_draws INT64 NOT NULL,
    overall_loses INT64 NOT NULL,
    overall_goals_for INT64 NOT NULL,
    overall_goals_against INT64 NOT NULL
);
